package vista;

import controlador.Ctrl_Operacion;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Operacion;

/**
 *
 * @author josez
 */
public class InterOperacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterProducto
     */
    public InterOperacion() {

        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nueva Operación");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_departamento = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_tiempoEjecuccion = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jComboBox_departamento = new javax.swing.JComboBox<>();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Operación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cantidad.setText("Tiempo ejecucción:");
        getContentPane().add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_descripcion.setText("Descripción:");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, -1));

        lbl_departamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_departamento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_departamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_departamento.setText("departamento");
        getContentPane().add(lbl_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, -1));

        txt_descripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        txt_tiempoEjecuccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_tiempoEjecuccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tiempoEjecuccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tiempoEjecuccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, 30));

        jComboBox_departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione departamento:", " " }));
        getContentPane().add(jComboBox_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 6, 390, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tiempoEjecuccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tiempoEjecuccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tiempoEjecuccionActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        // TODO add your handling code here:
        String departamentoSeleccion = "";
        departamentoSeleccion = jComboBox_departamento.getSelectedItem().toString().trim();
        Operacion operacion = new Operacion();
        Ctrl_Operacion controlOperacion = new Ctrl_Operacion();
        if (!txt_descripcion.getText().isEmpty() && !txt_tiempoEjecuccion.getText().isEmpty() && !jComboBox_departamento.getSelectedItem().equals("Seleccione departamento:")) {
            //JOptionPane.showMessageDialog(null,"Correcto");
            if (!controlOperacion.existeOperacion(txt_descripcion.getText().trim())) {
                operacion.setDescripcion(txt_descripcion.getText().trim());
                operacion.setTiempoEjecuccion(Integer.parseInt(txt_tiempoEjecuccion.getText().trim()));
                operacion.setDepartamento((departamentoSeleccion));

                if (controlOperacion.guardar(operacion)) {
                    JOptionPane.showMessageDialog(null, "Registro Exitoso");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La operacion existe en la base de datos");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        }
        // Metodo limpiar
        this.LimpiarCampos();


    }//GEN-LAST:event_jButton_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JComboBox<String> jComboBox_departamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_departamento;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_tiempoEjecuccion;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * metodo limpiar campos
     */
    private void LimpiarCampos() {
        txt_descripcion.setText("");
        txt_tiempoEjecuccion.setText("");
        jComboBox_departamento.setSelectedItem("Seleccione departamento:");
        
    }
}
