package vista;

import conexion.Conexion;
import controlador.Ctrl_Asignacion;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Asignacion;

/**
 *
 * @author josez
 */
public class InterGestionarAsignacion extends javax.swing.JInternalFrame {

    private int idAsignacion;

    public InterGestionarAsignacion() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Evaluar Asignacion");
        this.CargarTablaAsignaciones();

        //insetar imagen el jlabelwallpaper
        ImageIcon wallpaper = new ImageIcon("src/img/fondo3.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_asignacionEvaluar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_asignaciones = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_evaluacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_evaluacion = new javax.swing.JTextArea();
        jLabel_evaluacion1 = new javax.swing.JLabel();
        jTextField_idAsignacion = new javax.swing.JTextField();
        jLabel_evaluacion2 = new javax.swing.JLabel();
        jLabel_evaluacion3 = new javax.swing.JLabel();
        jTextField_supervisor = new javax.swing.JTextField();
        jTextField_empleado = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_asignacionEvaluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_asignacionEvaluar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_asignacionEvaluar.setText("Evaluar Asiganciones");
        getContentPane().add(lbl_asignacionEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_asignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_asignaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(204, 255, 204));
        jButton_actualizar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 130, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_evaluacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_evaluacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_evaluacion.setText("Evaluacion:");
        jPanel3.add(jLabel_evaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, -1));

        jTextArea_evaluacion.setColumns(20);
        jTextArea_evaluacion.setRows(5);
        jScrollPane2.setViewportView(jTextArea_evaluacion);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 6, 290, 80));

        jLabel_evaluacion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_evaluacion1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_evaluacion1.setText("Codigo asignacion:");
        jPanel3.add(jLabel_evaluacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        jTextField_idAsignacion.setEnabled(false);
        jTextField_idAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idAsignacionActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_idAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, -1));

        jLabel_evaluacion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_evaluacion2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_evaluacion2.setText("Supervisor:");
        jPanel3.add(jLabel_evaluacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jLabel_evaluacion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_evaluacion3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_evaluacion3.setText("Empleado:");
        jPanel3.add(jLabel_evaluacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jTextField_supervisor.setEnabled(false);
        jTextField_supervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_supervisorActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        jTextField_empleado.setEnabled(false);
        jTextField_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_empleadoActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 870, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 6, 890, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        if (jTextArea_evaluacion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Realizar evaluación");
        } else {
            Asignacion asignacion = new Asignacion();
            Ctrl_Asignacion controlAsignacion = new Ctrl_Asignacion();
            asignacion.setEvaluacion(jTextArea_evaluacion.getText());

            if (controlAsignacion.evaluar(asignacion, idAsignacion)) {
                JOptionPane.showMessageDialog(null, "Asignacion evaluada");
                this.CargarTablaAsignaciones();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al evaluar");
            }
        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jTextField_idAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idAsignacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idAsignacionActionPerformed

    private void jTextField_supervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_supervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_supervisorActionPerformed

    private void jTextField_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_empleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JLabel jLabel_evaluacion;
    private javax.swing.JLabel jLabel_evaluacion1;
    private javax.swing.JLabel jLabel_evaluacion2;
    private javax.swing.JLabel jLabel_evaluacion3;
    public static javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable_asignaciones;
    private javax.swing.JTextArea jTextArea_evaluacion;
    private javax.swing.JTextField jTextField_empleado;
    private javax.swing.JTextField jTextField_idAsignacion;
    private javax.swing.JTextField jTextField_supervisor;
    private javax.swing.JLabel lbl_asignacionEvaluar;
    // End of variables declaration//GEN-END:variables
 /*
     * Metodo para limpiar campos tabla
     *  
     */
    private void Limpiar() {
        jTextArea_evaluacion.setText("");

    }

    /**
     * Metodo para caragar tabla cliente
     */
    private void CargarTablaAsignaciones() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select * from tb_asignacion";
        Statement st;

        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarAsignacion.jTable_asignaciones = new JTable(model);
            InterGestionarAsignacion.jScrollPane1.setViewportView(InterGestionarAsignacion.jTable_asignaciones);

            model.addColumn("N°");
            model.addColumn("CODIGO OPERACION");
            model.addColumn("DESCRIPCION");
            model.addColumn("SUPERVISOR");
            model.addColumn("EMPLEADO");
            model.addColumn("FECHA INICIO");
            model.addColumn("FECHA FIN");
            model.addColumn("EVALUACION");

            while (rs.next()) {
                Object fila[] = new Object[8];
                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);

            }
            con.close();

        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla asignacion" + e);
        }

        jTable_asignaciones.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_asignaciones.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idAsignacion = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosAsignacionSeleccionado(idAsignacion);//metodo
                }
            }
        });

    }

    /**
     * Metodos que envia datos seleccionados de la tabla gestionar cliente
     */
    private void EnviarDatosAsignacionSeleccionado(int idAsignacion) {

        try {

            Connection con = Conexion.conectar();
            PreparedStatement pst1 = con.prepareStatement("select * from tb_asignacion where idAsignacion = '" + idAsignacion + "'");
            ResultSet rs = pst1.executeQuery();

            if (rs.next()) {
                jTextField_idAsignacion.setText(Integer.toString(idAsignacion));
                jTextArea_evaluacion.setText(rs.getString("evaluacion"));
                int idEmpleado = rs.getInt("idEmpleado");
                int idSupervisor = rs.getInt("idSupervisor");

                PreparedStatement pst3 = con.prepareStatement("select nombre, apellido from tb_usuario where idUsuario= '" + idEmpleado + "'");
                ResultSet rs3 = pst3.executeQuery();
                if (rs3.next()) {
                    jTextField_empleado.setText( rs3.getString("nombre")+" "+ rs3.getString("apellido"));
                }
                rs3.close();

                PreparedStatement pst4 = con.prepareStatement("select nombre, apellido from tb_usuario where idUsuario= '" + idSupervisor + "'");
                ResultSet rs4 = pst4.executeQuery();
                if (rs4.next()) {
                    jTextField_supervisor.setText(rs4.getString("nombre")+" "+ rs4.getString("apellido"));
                }
                rs4.close();
            }
            rs.close();
            con.close();
        } catch (SQLException e) {
            System.out.println("Error Seleccionar Asignacion");
        }
    }

    /**
     * Metodo para obtener noombre de Empleado
     *
     * @return
     */
}
