package vista;


import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JTextField;
import static vista.FrmMenu.jDestokPane_menu;

/**
 *
 * @author josez
 */
public class InterGraficas extends javax.swing.JInternalFrame {
    public static String fecha_inicio ="",fecha_fin ="";
   

    int obetenerIdCategoriaCombo = 0;

    /**
     * Creates new form InterProducto
     */
    public InterGraficas() {
        

        initComponents();
        this.setSize(new Dimension(450, 300));
        this.setTitle("Historial de Ventas");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        jButton_Guardar = new javax.swing.JButton();
        jDateChooser_fechaInicio = new com.toedter.calendar.JDateChooser();
        jDateChooser_fechaFin = new com.toedter.calendar.JDateChooser();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione rango de fechas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_cantidad.setText("Fecha fin:");
        getContentPane().add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, -1));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre.setText("Fecha inicio:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jButton_Guardar.setText("Graficar Ventas");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 200, 40));

        jDateChooser_fechaInicio.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fechaInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jDateChooser_fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, -1));

        jDateChooser_fechaFin.setDateFormatString("yyyy-MM-dd");
        jDateChooser_fechaFin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jDateChooser_fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 6, 440, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        fecha_inicio = ((JTextField)jDateChooser_fechaInicio.getDateEditor().getUiComponent()).getText();
        fecha_fin = ((JTextField)jDateChooser_fechaFin.getDateEditor().getUiComponent()).getText();
        
        InterGraficarVentas interGraficarVentas = new InterGraficarVentas();
       jDestokPane_menu.add(interGraficarVentas);
       interGraficarVentas.setVisible(true);
        
        
        

    }//GEN-LAST:event_jButton_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaFin;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_nombre;
    // End of variables declaration//GEN-END:variables

}