package vista;

import controlador.Ctrl_Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;

/**
 *
 * @author josez
 */
public class InterUsuario extends javax.swing.JInternalFrame {

    int obetenerIdCategoriaCombo = 0;

    /**
     * Creates new form InterProducto
     */
    public InterUsuario() {

        initComponents();
        this.setSize(new Dimension(600, 350));
        this.setTitle("Nuevo Empleado");
        txt_password.setVisible(true);
        txt_password_visible.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_iva = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        txt_telefono = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        Checkb_verclave = new javax.swing.JCheckBox();
        txt_password_visible = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        txt_cargo = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_correoElectronico = new javax.swing.JTextField();
        lbl_cargo = new javax.swing.JLabel();
        lbl_iva2 = new javax.swing.JLabel();
        lbl_iva4 = new javax.swing.JLabel();
        lbl_iva5 = new javax.swing.JLabel();
        lbl_iva6 = new javax.swing.JLabel();
        jDateChooser_fechaIngreso = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        lbl_cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cantidad.setText("Apellido:");
        getContentPane().add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 80, -1));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        lbl_precio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_precio.setText("Usuario:");
        getContentPane().add(lbl_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        lbl_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_descripcion.setText("Password:");
        getContentPane().add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, -1));

        lbl_iva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_iva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iva.setText("Telefono:");
        getContentPane().add(lbl_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, -1));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, -1));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 170, -1));

        txt_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));

        jButton_Guardar.setBackground(new java.awt.Color(0, 204, 204));
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 40));

        txt_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 170, -1));

        txt_password.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 170, -1));

        Checkb_verclave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Checkb_verclaveMouseClicked(evt);
            }
        });
        getContentPane().add(Checkb_verclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        txt_password_visible.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txt_password_visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_visibleActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password_visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 170, -1));

        txt_rut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutActionPerformed(evt);
            }
        });
        getContentPane().add(txt_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));

        txt_cargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cargoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));

        txt_direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, -1));

        txt_correoElectronico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_correoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoElectronicoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, -1));

        lbl_cargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cargo.setText("Cargo:");
        getContentPane().add(lbl_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, -1));

        lbl_iva2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_iva2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iva2.setText("Direccion:");
        getContentPane().add(lbl_iva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        lbl_iva4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_iva4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iva4.setText("Rut:");
        getContentPane().add(lbl_iva4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        lbl_iva5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_iva5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iva5.setText("Email:");
        getContentPane().add(lbl_iva5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 80, -1));

        lbl_iva6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_iva6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_iva6.setText("F. Ingreso:");
        getContentPane().add(lbl_iva6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, -1));
        getContentPane().add(jDateChooser_fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        if (txt_nombre.getText().isEmpty() | txt_apellido.getText().isEmpty() | txt_usuario.getText().isEmpty()
                | txt_password.getText().isEmpty() | txt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            //Validar si usuario esta registrado
            Usuario usuario = new Usuario();

            Ctrl_Usuario controlUsuario = new Ctrl_Usuario();
            if (!controlUsuario.existeUsuario(txt_usuario.getText().trim())) {
                usuario.setNombre(txt_nombre.getText().trim());
                usuario.setApellido(txt_apellido.getText().trim());
                usuario.setRut(txt_rut.getText().trim());
                usuario.setUsuario(txt_usuario.getText().trim());
                usuario.setPassword(txt_password.getText().trim());
                usuario.setCargo(txt_cargo.getText().trim());
                usuario.setTelefono(txt_telefono.getText().trim());
                usuario.setCorreoElectronico(txt_correoElectronico.getText().trim());
                usuario.setDireccion(txt_direccion.getText().trim());
                usuario.setEstado(1);
               // Obtener fecha de ingreso
                Date fechaSeleccionadaI = jDateChooser_fechaIngreso.getDate();
                if (fechaSeleccionadaI != null) {
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String fechaComoString = sdf.format(fechaSeleccionadaI);
                    usuario.setFechaIngreso(fechaComoString);
                }
                
                // No establecer fecha de egreso
                usuario.setFechaEgreso(null);

                if (controlUsuario.guardar(usuario)) {
                    JOptionPane.showMessageDialog(null, "Usuario Guardado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar Usuario");
                }
                this.LimpiarCampos();
                

                

            } else {
                JOptionPane.showMessageDialog(null, "Usuario ya esta registrado, ingrese nuevo usuario");
            }
        }

    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_password_visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_visibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_visibleActionPerformed

    private void Checkb_verclaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Checkb_verclaveMouseClicked
        // TODO add your handling code here:

        if (Checkb_verclave.isSelected() == true) {

            char[] passwordIngresado = txt_password.getPassword();

            txt_password_visible.setText(new String(passwordIngresado));
            txt_password.setVisible(false);
            txt_password_visible.setVisible(true);
        } else {
            String passwIngresado = txt_password_visible.getText().trim();
            txt_password.setText(passwIngresado);
            txt_password.setVisible(true);
            txt_password_visible.setVisible(false);

        }
    }//GEN-LAST:event_Checkb_verclaveMouseClicked

    private void txt_rutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutActionPerformed

    private void txt_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cargoActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_correoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoElectronicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Checkb_verclave;
    private javax.swing.JButton jButton_Guardar;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_iva;
    private javax.swing.JLabel lbl_iva2;
    private javax.swing.JLabel lbl_iva4;
    private javax.swing.JLabel lbl_iva5;
    private javax.swing.JLabel lbl_iva6;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_correoElectronico;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_password_visible;
    private javax.swing.JTextField txt_rut;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * metodo limpiar campos
     */
    private void LimpiarCampos() {
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_rut.setText("");
        txt_usuario.setText("");
        txt_password.setText("");
        txt_cargo.setText("");
        txt_telefono.setText("");
        txt_correoElectronico.setText("");
        txt_direccion.setText("");
        jDateChooser_fechaIngreso.setDate(null);
        
    }
}
